name: 'Grid.ai Status'
description: 'Grid.ai Status'
inputs:
  obj-type:  # id of input
    required: true
    default: ""
    description: "[run, datastore, session, cluster]"
  obj-id:  # id of input
    required: true
    default: ""
    description: "grid identifier from the grid run, grid datastore, grid session, grid cluster"
  script-args:
    required: false
    default: ""
outputs:
  obj-status:
    value: ${{ steps.gridai-obj-status.outputs.obj-status }}
    description: "comma delimited status all of experiments. ex: succeeded,succeeded,stopped"
  obj-tally:
    value: ${{ steps.gridai-obj-status.outputs.obj-tally }}
    description: "comma delimited tally status codes. ex: 2 succeeded,1 stopped"
  obj-summary:
    value: ${{ steps.gridai-obj-status.outputs.obj-summary }}
    description: "comma delimited unique status codes. ex: succeeded,stopped"
  obj-exit-code:
    value: ${{ steps.gridai-obj-status.outputs.obj-exit-code }}
    description: "0 if exited finding the supplied status, 1 otherwise"
runs:
  using: "composite"
  steps:
    - id: gridai-obj-status
      run: ${{ github.action_path }}/gridai_obj_status.sh ${{ inputs.script-args }} ${{ inputs.obj-type }} ${{ inputs.obj-id }}
      shell: bash

