name: 'Grid.ai Status'
description: 'Grid.ai Status'
inputs:
  obj-type:  # id of input
    required: true
    default: ""
    description: "[run, datastore, session, cluster]"
  obj-id:  # id of input
    required: true
    default: ""
    description: "grid identifier from the grid run, grid datastore, grid session, grid cluster"
  script-args:
    required: false
    default: ""
outputs:
  obj-status:
    value: ${{ steps.gridai-obj-status.outputs.obj-status }}
  obj-summary:
    value: ${{ steps.gridai-obj-status.outputs.obj-summary }}
  ovj-exit-code:
    value: ${{ steps.gridai-obj-status.outputs.obj-exit-code }}
runs:
  using: "composite"
  steps:
    - id: gridai-obj-status
      run: ${{ github.action_path }}/gridai_obj_status.sh ${{ inputs.script-args }} ${{ inputs.obj-type }} ${{ inputs.obj-id }}
      shell: bash

