# composite action must be 
#  named action.yml or action.yaml
#  create a Tag and a Release for our repo.
name: 'Hello World'
description: 'Greet someone'
inputs:
  obj-type:  # id of input
    required: true
    default: ""
  obj-id:  # id of input
    required: true
    default: ""
  script-args:
    required: false
    default: ""
outputs:
  obj-status:
    value: ${{ steps.gridai-obj-status.outputs.obj-status }}
  obj-summary:
    value: ${{ steps.gridai-obj-status.outputs.obj-summary }}
  ovj-exit-code:
    value: ${{ steps.gridai-obj-status.outputs.obj-exit-code }}
runs:
  using: "composite"
  steps:
    - id: gridai-obj-status
      run: ${{ github.action-path }}/gridai_obj_status.sh ${{ inputs.script-args }} ${{ inputs.obj-type }} ${{ inputs.obj-id }}
      shell: bash

